---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echo-dev
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: echo-dev
  chart:
    git: git@github.com:Looty/helm-operator-get-started.git
    path: charts/echo
    ref: master
  values:
    image:
      repository: looty10/echo
      tag: dev-qburegpp
    replicaCount: 1
    secret:
      url:
        value: bW9uZ29kYjovL3VzZXI6cGFzc3dvcmRAZWNoby1tb25nb2RiLWRldi0wLmVjaG8tbW9uZ29kYi1kZXYtaGVhZGxlc3MuZGV2LnN2Yy5jbHVzdGVyLmxvY2FsOjI3MDE3LGVjaG8tbW9uZ29kYi1kZXYtMS5lY2hvLW1vbmdvZGItZGV2LWhlYWRsZXNzLmRldi5zdmMuY2x1c3Rlci5sb2NhbDoyNzAxNyxlY2hvLW1vbmdvZGItZGV2LTAuZWNoby1tb25nb2RiLWRldi1oZWFkbGVzcy5kZXYuc3ZjLmNsdXN0ZXIubG9jYWw6MjcwMTcvZWNob3M=
    ingress:
      domain: dev.erezcowsay229q8sd5aks.tk
      service: echo-dev
    issuer:
      privateKeyName: echo-dev