apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    nginx.org/proxy-connect-timeout: {{ .Values.ingress.connectTimeout }}
    cert-manager.io/cluster-issuer: {{ include "echo.fullname" . }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
      - {{ .Values.ingress.domain }}
      secretName: {{ .Values.ingress.secretName }}
  rules:
    - host: {{ .Values.ingress.domain }}
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ingress.service }}
                port: 
                  number: {{ .Values.container.port }}