apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    nginx.org/proxy-connect-timeout: {{ .Values.ingress.connectTimeout }}
    cert-manager.io/cluster-issuer: {{ .Values.issuer.privateKeyName }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
      - {{ .Values.ingress.echoTls.domain }}
      secretName: {{ .Values.ingress.echoTls.secretName }}
  rules:
    - host: {{ .Values.ingress.echoTls.domain }}
        http:
          paths:
            - path: "/"
              pathType: Prefix
              backend:
                service:
                  name: {{ .Values.ingress.nginxHosts.service }}
                  port: 
                    number: {{ .Values.container.port }}