---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echo-rc
  namespace: stg
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:stg-*
spec:
  releaseName: echo-rc
  chart:
    git: git@github.com:Looty/helm-operator-get-started.git
    path: charts/echo
    ref: master
  values:
    image:
      repository: looty10/echo
      tag: stg-eggihjvb
    replicaCount: 1
    secret:
      url:
        value: bW9uZ29kYjovL3VzZXI6cGFzc3dvcmRAbW9uZ29kYi0wLm1vbmdvZGItaGVhZGxlc3Muc3RnLnN2Yy5jbHVzdGVyLmxvY2FsOjI3MDE3LG1vbmdvZGItMS5tb25nb2RiLWhlYWRsZXNzLnN0Zy5zdmMuY2x1c3Rlci5sb2NhbDoyNzAxNyxtb25nb2RiLTIubW9uZ29kYi1oZWFkbGVzcy5zdGcuc3ZjLmNsdXN0ZXIubG9jYWw6MjcwMTcvZWNob3M=
    # hpa:
    #   enabled: true
    #   maxReplicas: 10
    #   cpu: 50
    #   memory: 256Mi