---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echo-rc
  namespace: stg
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:stg-*
spec:
  releaseName: echo-rc
  chart:
    git: git@github.com:Looty/helm-operator-get-started.git
    path: charts/echo
    ref: master
  values:
    image:
      repository: looty10/echo
      tag: stg-snasjahs
    replicaCount: 1
    secret:
      url:
        value: bW9uZ29kYjovL3VzZXI6cGFzc3dvcmRAZWNoby1tb25nb2RiLXJjLTAuZWNoby1tb25nb2RiLXJjLWhlYWRsZXNzLnJjLnN2Yy5jbHVzdGVyLmxvY2FsOjI3MDE3LGVjaG8tbW9uZ29kYi1yYy0xLmVjaG8tbW9uZ29kYi1yYy1oZWFkbGVzcy5yYy5zdmMuY2x1c3Rlci5sb2NhbDoyNzAxNyxlY2hvLW1vbmdvZGItcmMtMC5lY2hvLW1vbmdvZGItcmMtaGVhZGxlc3MucmMuc3ZjLmNsdXN0ZXIubG9jYWw6MjcwMTcvZWNob3M=
    ingress:
      echoTls:
        domain: prod.ii2g3t2-g25di89.tk
        service: echo-prod-echo
    # hpa:
    #   enabled: true
    #   maxReplicas: 10
    #   cpu: 50
    #   memory: 256M